<?php
/**
 * @file
 * Contains rightclick_block_highlighted.module
 */

/*
 * Implements hook_preprocess_HOOK().
 * Alter highlighted block to add classes for constrained and backgound color
 */
function rightclick_block_highlighted_preprocess_block(&$variables) {

  /*
   * Get the Block object if it exists.
   */
  if (!empty($variables['content']['#block_content'])) {
    $block = $variables['content']['#block_content'];
    $blockType = $block->bundle();

    /*
     * Check if the block type is 'rightclick_highlightedblock'.
     */
    if ($blockType == 'rightclick_highlightedblock') {

      /*
       * Add a common CSS class for highlighted block
       * same for "block highlighted" and "view block highlighted"
       */
      $variables['attributes']['class'][] = 'highlighted-block';

      /*
       * Check the value of the 'field_high_constrained' field and add an extra wrapper for constrained.
       */
      if ($block->get('field_high_constrained')->getValue()[0]['value'] == 1) {
        $variables['content']['#theme_wrappers']['container']['#attributes']['class'] = array(
          'constrained',
        );
      }

      /*
       * Add a CSS class for background color
       */
      if ($block->get('field_high_bgcolor')->getValue()[0]['value']) {
        $variables['attributes']['class'][] = 'bg-' . $block->get('field_high_bgcolor')
            ->getValue()[0]['value'];
      }
    }
  }
}